FROM nginxinc/nginx-unprivileged:1.20
#COPY ./nginx.conf /etc/nginx/nginx.conf
#RUN rm -rf /etc/nginx/html/*
#COPY ./html /etc/nginx/html
#WORKDIR /app
#EXPOSE <PORT_NUMBER>
CMD ["nginx", "-g", "daemon off;"]